SELECT indice,
  CASE 
  WHEN a.ARMAS_MEDIOSI IN ('NO REGISTRA', 'NO REPORTADO') THEN (SELECT ARMAS_MEDIOSI FROM {{ ref("moda_armas") }})
  WHEN a.ARMAS_MEDIOSI = 'CORTOPUNZANTES' THEN 'ARMA BLANCA / CORTOPUNZANTE'
  ELSE a.ARMAS_MEDIOSI 
  END AS ARMAS_MEDIOS
FROM {{ source("Hurto","Hurtos") }} AS a