SELECT GENERO, AGRUPA_EDAD_PERSONA,COUNT(*) AS conteo
FROM {{ source("Hurto","Hurtos") }}
WHERE AGRUPA_EDAD_PERSONA != "NO REPORTADO" AND AGRUPA_EDAD_PERSONA != "NO REPORTA"
GROUP BY GENERO, AGRUPA_EDAD_PERSONA