SELECT indice,
  CASE 
    WHEN a.AGRUPA_EDAD_PERSONA != 'ADULTOS' AND a.AGRUPA_EDAD_PERSONA != 'ADOLESCENTES' AND a.AGRUPA_EDAD_PERSONA !='MENORES' THEN (SELECT AGRUPA_EDAD_PERSONA FROM {{ ref("moda") }} WHERE GENERO=moda.GENERO LIMIT 1)
    ELSE a.AGRUPA_EDAD_PERSONA
  END AS AGRUPA_EDAD_PERSONA
FROM {{ source("Hurto","Hurtos") }} AS a